/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.game_request;

import java.awt.Color;
import java.awt.Rectangle;
import javax.swing.BorderFactory;

/**
 *
 * @author Others
 */
public class GameRequestOutgoingFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameRequestIncoming
     */
    public GameRequestOutgoingFrame() {
        initComponents();
        statusLabel.setBackground(new java.awt.Color(0,0,0,0));
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.CYAN));
        setLocationRelativeTo(null);
    }
    
    private int posX;
    private int posY;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acceptionLabel = new javax.swing.JLabel();
        gameLabel = new javax.swing.JLabel();
        connectionLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        ipLabel = new javax.swing.JLabel();
        peerIP = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        peerPort = new javax.swing.JLabel();
        statusLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(372, 146));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acceptionLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        acceptionLabel.setFocusable(false);
        getContentPane().add(acceptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 50, 50));

        gameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        gameLabel.setFocusable(false);
        getContentPane().add(gameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 50, 50));

        connectionLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        connectionLabel.setFocusable(false);
        getContentPane().add(connectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 50));

        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.setFocusable(false);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 83, -1));

        ipLabel.setText("IP:");
        ipLabel.setFocusable(false);
        getContentPane().add(ipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        peerIP.setFocusable(false);
        getContentPane().add(peerIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 90, -1));

        portLabel.setText("Port:");
        portLabel.setFocusable(false);
        getContentPane().add(portLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 30, -1));

        peerPort.setFocusable(false);
        getContentPane().add(peerPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        statusLabel.setEditable(false);
        statusLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusLabel.setBorder(null);
        statusLabel.setFocusable(false);
        statusLabel.setOpaque(false);
        getContentPane().add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, -1));

        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 30, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
            posX = evt.getX();
            posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
            Rectangle rectangle = getBounds();
            setBounds(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY, rectangle.width, rectangle.height);        
    }//GEN-LAST:event_formMouseDragged

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
        // TODO add your handling code here:
        onCancled();
        dispose();
    }//GEN-LAST:event_cancelButtonMousePressed

    protected void onCancled() {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameRequestOutgoingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameRequestOutgoingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameRequestOutgoingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameRequestOutgoingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameRequestOutgoingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel acceptionLabel;
    protected javax.swing.JButton cancelButton;
    protected javax.swing.JLabel connectionLabel;
    protected javax.swing.JLabel gameLabel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel peerIP;
    public javax.swing.JLabel peerPort;
    private javax.swing.JLabel portLabel;
    public javax.swing.JTextField statusLabel;
    // End of variables declaration//GEN-END:variables
}
